#!/bin/bash
#
# Script for safe remove files and directories

#check if exist /RECYCLE
if [ -e ~/RECYCLE ]
then
	if cd ~/RECYCLE
		then
#			echo 'RECYCLE exist / out ls ~/RECYCLE/:'
#			ls ~/RECYCLE
			find ~/RECYCLE/* -mtime 8 -exec rm -fv {} \;
	fi
else
	mkdir ~/RECYCLE
fi
